### ISSUE TITLE
ERROR: Invalid private key provided

### ISSUE THREAD

**Issue by se8820726** [TRON-US/eCommerce-hello-world#3]
hi

according to part 1 of your walkthrough
I maked a _.env_ file in root of project with this content:
`PK="my private key extracted from TronLink";`

but in part 3 when I enter `tronbox migrate --reset --network shasta` in terminal get me this error:
**ERROR: Invalid private key provided**

now how can I solve this problem ?

**Comment by UjwalBattar** [comment]
You have to insert your actual private key there. Which you can find in TronLink.

**Comment by se8820726** [comment]
problem solved.
I should be enter privatekey without any (") and (') characters

**Comment by UjwalBattar** [comment]
Great! Generally speaking, most env variables should be without quotes. I am glad you were able to solve that! Hope you enjoyed following through the tutorial.
